apiVersion: v2
name: karakeep
description: A Helm chart for Karakeep - AI-powered knowledge management and bookmark organizer
type: application
version: 2.4.0
appVersion: 0.27.1
icon: https://avatars.githubusercontent.com/u/202258986
maintainers:
  - name: facorazza
    email: git@facorazza.com
dependencies:
  - name: boilerplate
    version: 0.15.1
    repository: "https://self-hosters-by-night.github.io/helm-charts"
  - name: chrome
    version: 0.5.0
    repository: https://self-hosters-by-night.github.io/helm-charts
    condition: chrome.enabled
  - name: meilisearch
    version: 0.15.0
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: meilisearch.enabled
