apiVersion: v2
name: lldap
description: A Helm chart for LLDAP, a lightweight authentication server that provides an opinionated and simplified LDAP interface for authentication.
type: application
version: 0.4.0
appVersion: "2025-05-19"
icon: https://raw.githubusercontent.com/self-hosters-by-night/helm-charts/refs/heads/main/assets/lldap.png
annotations:
  artifacthub.io/category: security
keywords:
  - ldap
  - authentication
  - directory
maintainers:
  - name: facorazza
    email: git@facorazza.com
dependencies:
  - name: boilerplate
    version: 0.15.1
    repository: "https://self-hosters-by-night.github.io/helm-charts"
  - name: postgres
    version: 0.13.0
    repository: "https://self-hosters-by-night.github.io/helm-charts"
